/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BooleanFilterInput: { // input type
    and?: Array<boolean | null> | null; // [Boolean]
    between?: Array<boolean | null> | null; // [Boolean]
    contains?: boolean | null; // Boolean
    containsi?: boolean | null; // Boolean
    endsWith?: boolean | null; // Boolean
    eq?: boolean | null; // Boolean
    eqi?: boolean | null; // Boolean
    gt?: boolean | null; // Boolean
    gte?: boolean | null; // Boolean
    in?: Array<boolean | null> | null; // [Boolean]
    lt?: boolean | null; // Boolean
    lte?: boolean | null; // Boolean
    ne?: boolean | null; // Boolean
    nei?: boolean | null; // Boolean
    not?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    notContains?: boolean | null; // Boolean
    notContainsi?: boolean | null; // Boolean
    notIn?: Array<boolean | null> | null; // [Boolean]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<boolean | null> | null; // [Boolean]
    startsWith?: boolean | null; // Boolean
  }
  ComponentSectionsCtaFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsCtaFiltersInput'] | null> | null; // [ComponentSectionsCtaFiltersInput]
    body?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    buttonLabel?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    buttonLink?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    heading?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ComponentSectionsCtaFiltersInput'] | null; // ComponentSectionsCtaFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsCtaFiltersInput'] | null> | null; // [ComponentSectionsCtaFiltersInput]
  }
  ComponentSectionsCtaInput: { // input type
    body?: string | null; // String
    buttonLabel?: string | null; // String
    buttonLink?: string | null; // String
    heading?: string | null; // String
    id?: string | null; // ID
  }
  ComponentSectionsInfoBlockFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsInfoBlockFiltersInput'] | null> | null; // [ComponentSectionsInfoBlockFiltersInput]
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    icon?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ComponentSectionsInfoBlockFiltersInput'] | null; // ComponentSectionsInfoBlockFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsInfoBlockFiltersInput'] | null> | null; // [ComponentSectionsInfoBlockFiltersInput]
    title?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
  }
  ComponentSectionsInfoBlockInput: { // input type
    description?: string | null; // String
    icon?: string | null; // String
    id?: string | null; // ID
    title?: string | null; // String
  }
  ComponentSectionsInfoBlocksFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsInfoBlocksFiltersInput'] | null> | null; // [ComponentSectionsInfoBlocksFiltersInput]
    blocks?: NexusGenInputs['ComponentSectionsInfoBlockFiltersInput'] | null; // ComponentSectionsInfoBlockFiltersInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    heading?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    intro?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ComponentSectionsInfoBlocksFiltersInput'] | null; // ComponentSectionsInfoBlocksFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsInfoBlocksFiltersInput'] | null> | null; // [ComponentSectionsInfoBlocksFiltersInput]
  }
  ComponentSectionsInfoBlocksInput: { // input type
    blocks?: Array<NexusGenInputs['ComponentSectionsInfoBlockInput'] | null> | null; // [ComponentSectionsInfoBlockInput]
    description?: string | null; // String
    heading?: string | null; // String
    id?: string | null; // ID
    intro?: string | null; // String
  }
  ComponentSectionsMediaCollectionFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsMediaCollectionFiltersInput'] | null> | null; // [ComponentSectionsMediaCollectionFiltersInput]
    categoryLabel?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    ctaLink?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    items?: NexusGenInputs['ComponentSectionsMediaCollectionItemFiltersInput'] | null; // ComponentSectionsMediaCollectionItemFiltersInput
    not?: NexusGenInputs['ComponentSectionsMediaCollectionFiltersInput'] | null; // ComponentSectionsMediaCollectionFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsMediaCollectionFiltersInput'] | null> | null; // [ComponentSectionsMediaCollectionFiltersInput]
    showItemNumbers?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    subtitle?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    title?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    variant?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
  }
  ComponentSectionsMediaCollectionInput: { // input type
    categoryLabel?: string | null; // String
    ctaLink?: string | null; // String
    description?: string | null; // String
    id?: string | null; // ID
    items?: Array<NexusGenInputs['ComponentSectionsMediaCollectionItemInput'] | null> | null; // [ComponentSectionsMediaCollectionItemInput]
    showItemNumbers?: boolean | null; // Boolean
    subtitle?: string | null; // String
    title?: string | null; // String
    variant?: NexusGenEnums['ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT'] | null; // ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT
  }
  ComponentSectionsMediaCollectionItemFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsMediaCollectionItemFiltersInput'] | null> | null; // [ComponentSectionsMediaCollectionItemFiltersInput]
    not?: NexusGenInputs['ComponentSectionsMediaCollectionItemFiltersInput'] | null; // ComponentSectionsMediaCollectionItemFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsMediaCollectionItemFiltersInput'] | null> | null; // [ComponentSectionsMediaCollectionItemFiltersInput]
    subtitleOverride?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    titleOverride?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    video?: NexusGenInputs['VideoFiltersInput'] | null; // VideoFiltersInput
  }
  ComponentSectionsMediaCollectionItemInput: { // input type
    id?: string | null; // ID
    imageOverride?: string | null; // ID
    subtitleOverride?: string | null; // String
    titleOverride?: string | null; // String
    video?: string | null; // ID
  }
  ComponentSectionsPromoBannerFiltersInput: { // input type
    and?: Array<NexusGenInputs['ComponentSectionsPromoBannerFiltersInput'] | null> | null; // [ComponentSectionsPromoBannerFiltersInput]
    ctaLink?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    heading?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    intro?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ComponentSectionsPromoBannerFiltersInput'] | null; // ComponentSectionsPromoBannerFiltersInput
    or?: Array<NexusGenInputs['ComponentSectionsPromoBannerFiltersInput'] | null> | null; // [ComponentSectionsPromoBannerFiltersInput]
  }
  ComponentSectionsPromoBannerInput: { // input type
    ctaLink?: string | null; // String
    description?: string | null; // String
    heading?: string | null; // String
    id?: string | null; // ID
    intro?: string | null; // String
  }
  DateFilterInput: { // input type
    and?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    between?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    contains?: NexusGenScalars['Date'] | null; // Date
    containsi?: NexusGenScalars['Date'] | null; // Date
    endsWith?: NexusGenScalars['Date'] | null; // Date
    eq?: NexusGenScalars['Date'] | null; // Date
    eqi?: NexusGenScalars['Date'] | null; // Date
    gt?: NexusGenScalars['Date'] | null; // Date
    gte?: NexusGenScalars['Date'] | null; // Date
    in?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    lt?: NexusGenScalars['Date'] | null; // Date
    lte?: NexusGenScalars['Date'] | null; // Date
    ne?: NexusGenScalars['Date'] | null; // Date
    nei?: NexusGenScalars['Date'] | null; // Date
    not?: NexusGenInputs['DateFilterInput'] | null; // DateFilterInput
    notContains?: NexusGenScalars['Date'] | null; // Date
    notContainsi?: NexusGenScalars['Date'] | null; // Date
    notIn?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    startsWith?: NexusGenScalars['Date'] | null; // Date
  }
  DateTimeFilterInput: { // input type
    and?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    between?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    contains?: NexusGenScalars['DateTime'] | null; // DateTime
    containsi?: NexusGenScalars['DateTime'] | null; // DateTime
    endsWith?: NexusGenScalars['DateTime'] | null; // DateTime
    eq?: NexusGenScalars['DateTime'] | null; // DateTime
    eqi?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    ne?: NexusGenScalars['DateTime'] | null; // DateTime
    nei?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    notContains?: NexusGenScalars['DateTime'] | null; // DateTime
    notContainsi?: NexusGenScalars['DateTime'] | null; // DateTime
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    startsWith?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ExperienceFiltersInput: { // input type
    and?: Array<NexusGenInputs['ExperienceFiltersInput'] | null> | null; // [ExperienceFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    isHomepage?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    locale?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    localizations?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
    not?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
    or?: Array<NexusGenInputs['ExperienceFiltersInput'] | null> | null; // [ExperienceFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    slug?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ExperienceInput: { // input type
    isHomepage?: boolean | null; // Boolean
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    sections?: NexusGenScalars['ExperienceSectionsDynamicZoneInput'][] | null; // [ExperienceSectionsDynamicZoneInput!]
    slug?: string | null; // String
  }
  FileInfoInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    name?: string | null; // String
  }
  FloatFilterInput: { // input type
    and?: Array<number | null> | null; // [Float]
    between?: Array<number | null> | null; // [Float]
    contains?: number | null; // Float
    containsi?: number | null; // Float
    endsWith?: number | null; // Float
    eq?: number | null; // Float
    eqi?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    ne?: number | null; // Float
    nei?: number | null; // Float
    not?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    notContains?: number | null; // Float
    notContainsi?: number | null; // Float
    notIn?: Array<number | null> | null; // [Float]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Float]
    startsWith?: number | null; // Float
  }
  I18NLocaleFiltersInput: { // input type
    and?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    code?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
    or?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  I18NLocaleInput: { // input type
    code?: string | null; // String
    name?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  IDFilterInput: { // input type
    and?: Array<string | null> | null; // [ID]
    between?: Array<string | null> | null; // [ID]
    contains?: string | null; // ID
    containsi?: string | null; // ID
    endsWith?: string | null; // ID
    eq?: string | null; // ID
    eqi?: string | null; // ID
    gt?: string | null; // ID
    gte?: string | null; // ID
    in?: Array<string | null> | null; // [ID]
    lt?: string | null; // ID
    lte?: string | null; // ID
    ne?: string | null; // ID
    nei?: string | null; // ID
    not?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    notContains?: string | null; // ID
    notContainsi?: string | null; // ID
    notIn?: Array<string | null> | null; // [ID]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [ID]
    startsWith?: string | null; // ID
  }
  IntFilterInput: { // input type
    and?: Array<number | null> | null; // [Int]
    between?: Array<number | null> | null; // [Int]
    contains?: number | null; // Int
    containsi?: number | null; // Int
    endsWith?: number | null; // Int
    eq?: number | null; // Int
    eqi?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    ne?: number | null; // Int
    nei?: number | null; // Int
    not?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    notContains?: number | null; // Int
    notContainsi?: number | null; // Int
    notIn?: Array<number | null> | null; // [Int]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Int]
    startsWith?: number | null; // Int
  }
  JSONFilterInput: { // input type
    and?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    between?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    contains?: NexusGenScalars['JSON'] | null; // JSON
    containsi?: NexusGenScalars['JSON'] | null; // JSON
    endsWith?: NexusGenScalars['JSON'] | null; // JSON
    eq?: NexusGenScalars['JSON'] | null; // JSON
    eqi?: NexusGenScalars['JSON'] | null; // JSON
    gt?: NexusGenScalars['JSON'] | null; // JSON
    gte?: NexusGenScalars['JSON'] | null; // JSON
    in?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    lt?: NexusGenScalars['JSON'] | null; // JSON
    lte?: NexusGenScalars['JSON'] | null; // JSON
    ne?: NexusGenScalars['JSON'] | null; // JSON
    nei?: NexusGenScalars['JSON'] | null; // JSON
    not?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    notContains?: NexusGenScalars['JSON'] | null; // JSON
    notContainsi?: NexusGenScalars['JSON'] | null; // JSON
    notIn?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    startsWith?: NexusGenScalars['JSON'] | null; // JSON
  }
  LongFilterInput: { // input type
    and?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    between?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    contains?: NexusGenScalars['Long'] | null; // Long
    containsi?: NexusGenScalars['Long'] | null; // Long
    endsWith?: NexusGenScalars['Long'] | null; // Long
    eq?: NexusGenScalars['Long'] | null; // Long
    eqi?: NexusGenScalars['Long'] | null; // Long
    gt?: NexusGenScalars['Long'] | null; // Long
    gte?: NexusGenScalars['Long'] | null; // Long
    in?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    lt?: NexusGenScalars['Long'] | null; // Long
    lte?: NexusGenScalars['Long'] | null; // Long
    ne?: NexusGenScalars['Long'] | null; // Long
    nei?: NexusGenScalars['Long'] | null; // Long
    not?: NexusGenInputs['LongFilterInput'] | null; // LongFilterInput
    notContains?: NexusGenScalars['Long'] | null; // Long
    notContainsi?: NexusGenScalars['Long'] | null; // Long
    notIn?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    startsWith?: NexusGenScalars['Long'] | null; // Long
  }
  PaginationArg: { // input type
    limit?: number | null; // Int
    page?: number | null; // Int
    pageSize?: number | null; // Int
    start?: number | null; // Int
  }
  ReviewWorkflowsWorkflowFiltersInput: { // input type
    and?: Array<NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null> | null; // [ReviewWorkflowsWorkflowFiltersInput]
    contentTypes?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null; // ReviewWorkflowsWorkflowFiltersInput
    or?: Array<NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null> | null; // [ReviewWorkflowsWorkflowFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    stageRequiredToPublish?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
    stages?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ReviewWorkflowsWorkflowInput: { // input type
    contentTypes?: NexusGenScalars['JSON'] | null; // JSON
    name?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    stageRequiredToPublish?: string | null; // ID
    stages?: Array<string | null> | null; // [ID]
  }
  ReviewWorkflowsWorkflowStageFiltersInput: { // input type
    and?: Array<NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null> | null; // [ReviewWorkflowsWorkflowStageFiltersInput]
    color?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
    or?: Array<NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null> | null; // [ReviewWorkflowsWorkflowStageFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    workflow?: NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null; // ReviewWorkflowsWorkflowFiltersInput
  }
  ReviewWorkflowsWorkflowStageInput: { // input type
    color?: string | null; // String
    name?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    workflow?: string | null; // ID
  }
  StringFilterInput: { // input type
    and?: Array<string | null> | null; // [String]
    between?: Array<string | null> | null; // [String]
    contains?: string | null; // String
    containsi?: string | null; // String
    endsWith?: string | null; // String
    eq?: string | null; // String
    eqi?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    ne?: string | null; // String
    nei?: string | null; // String
    not?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    notContains?: string | null; // String
    notContainsi?: string | null; // String
    notIn?: Array<string | null> | null; // [String]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  TimeFilterInput: { // input type
    and?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    between?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    contains?: NexusGenScalars['Time'] | null; // Time
    containsi?: NexusGenScalars['Time'] | null; // Time
    endsWith?: NexusGenScalars['Time'] | null; // Time
    eq?: NexusGenScalars['Time'] | null; // Time
    eqi?: NexusGenScalars['Time'] | null; // Time
    gt?: NexusGenScalars['Time'] | null; // Time
    gte?: NexusGenScalars['Time'] | null; // Time
    in?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    lt?: NexusGenScalars['Time'] | null; // Time
    lte?: NexusGenScalars['Time'] | null; // Time
    ne?: NexusGenScalars['Time'] | null; // Time
    nei?: NexusGenScalars['Time'] | null; // Time
    not?: NexusGenInputs['TimeFilterInput'] | null; // TimeFilterInput
    notContains?: NexusGenScalars['Time'] | null; // Time
    notContainsi?: NexusGenScalars['Time'] | null; // Time
    notIn?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    startsWith?: NexusGenScalars['Time'] | null; // Time
  }
  UploadFileFiltersInput: { // input type
    alternativeText?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    caption?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    ext?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    focalPoint?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    formats?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    hash?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    height?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    mime?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
    or?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    previewUrl?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider_metadata?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    size?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    url?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    width?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
  }
  UploadFileInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    ext?: string | null; // String
    focalPoint?: NexusGenScalars['JSON'] | null; // JSON
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash?: string | null; // String
    height?: number | null; // Int
    mime?: string | null; // String
    name?: string | null; // String
    previewUrl?: string | null; // String
    provider?: string | null; // String
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    size?: number | null; // Float
    url?: string | null; // String
    width?: number | null; // Int
  }
  UsersPermissionsLoginInput: { // input type
    identifier: string; // String!
    password: string; // String!
    provider: string; // String!
  }
  UsersPermissionsPermissionFiltersInput: { // input type
    action?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  UsersPermissionsPermissionInput: { // input type
    action?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    role?: string | null; // ID
  }
  UsersPermissionsRegisterInput: { // input type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
  UsersPermissionsRoleFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    permissions?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    type?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    users?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
  }
  UsersPermissionsRoleInput: { // input type
    description?: string | null; // String
    name?: string | null; // String
    permissions?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    type?: string | null; // String
    users?: Array<string | null> | null; // [ID]
  }
  UsersPermissionsUserFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    blocked?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    confirmed?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    email?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    username?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
  }
  UsersPermissionsUserInput: { // input type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    email?: string | null; // String
    password?: string | null; // String
    provider?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    role?: string | null; // ID
    username?: string | null; // String
  }
  VideoFiltersInput: { // input type
    and?: Array<NexusGenInputs['VideoFiltersInput'] | null> | null; // [VideoFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    documentId?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['VideoFiltersInput'] | null; // VideoFiltersInput
    or?: Array<NexusGenInputs['VideoFiltersInput'] | null> | null; // [VideoFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    slug?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    title?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  VideoInput: { // input type
    image?: string | null; // ID
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    slug?: string | null; // String
    title?: string | null; // String
  }
}

export interface NexusGenEnums {
  ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT: "carousel" | "collection" | "grid" | "hero" | "player"
  PublicationStatus: "draft" | "published"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
  ExperienceSectionsDynamicZoneInput: any
  I18NLocaleCode: any
  JSON: any
  Long: any
  Time: any
}

export interface NexusGenObjects {
  ComponentSectionsCta: { // root type
    body: string; // String!
    buttonLabel: string; // String!
    buttonLink: string; // String!
    heading: string; // String!
    id: string; // ID!
  }
  ComponentSectionsInfoBlock: { // root type
    description: string; // String!
    icon: string; // String!
    id: string; // ID!
    title: string; // String!
  }
  ComponentSectionsInfoBlocks: { // root type
    description?: string | null; // String
    heading?: string | null; // String
    id: string; // ID!
    intro?: string | null; // String
  }
  ComponentSectionsMediaCollection: { // root type
    categoryLabel?: string | null; // String
    ctaLink?: string | null; // String
    description?: string | null; // String
    id: string; // ID!
    showItemNumbers?: boolean | null; // Boolean
    subtitle?: string | null; // String
    title?: string | null; // String
    variant: NexusGenEnums['ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT']; // ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT!
  }
  ComponentSectionsMediaCollectionItem: { // root type
    id: string; // ID!
    subtitleOverride?: string | null; // String
    titleOverride?: string | null; // String
  }
  ComponentSectionsPromoBanner: { // root type
    ctaLink: string; // String!
    description: string; // String!
    heading: string; // String!
    id: string; // ID!
    intro?: string | null; // String
  }
  DeleteMutationResponse: { // root type
    documentId: string; // ID!
  }
  Error: { // root type
    message?: string | null; // String
  }
  Experience: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    isHomepage?: boolean | null; // Boolean
    locale?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    slug: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ExperienceEntity: {};
  ExperienceEntityResponse: {};
  ExperienceEntityResponseCollection: {};
  ExperienceRelationResponseCollection: {};
  I18NLocale: { // root type
    code?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: {};
  I18NLocaleEntityResponse: {};
  I18NLocaleEntityResponseCollection: {};
  I18NLocaleRelationResponseCollection: {};
  Mutation: {};
  Pagination: { // root type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Query: {};
  ResponseCollectionMeta: {};
  ReviewWorkflowsWorkflow: { // root type
    contentTypes: NexusGenScalars['JSON']; // JSON!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ReviewWorkflowsWorkflowEntity: {};
  ReviewWorkflowsWorkflowEntityResponse: {};
  ReviewWorkflowsWorkflowEntityResponseCollection: {};
  ReviewWorkflowsWorkflowRelationResponseCollection: {};
  ReviewWorkflowsWorkflowStage: { // root type
    color?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ReviewWorkflowsWorkflowStageEntity: {};
  ReviewWorkflowsWorkflowStageEntityResponse: {};
  ReviewWorkflowsWorkflowStageEntityResponseCollection: {};
  ReviewWorkflowsWorkflowStageRelationResponseCollection: {};
  UploadFile: { // root type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    ext?: string | null; // String
    focalPoint?: NexusGenScalars['JSON'] | null; // JSON
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height?: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl?: string | null; // String
    provider: string; // String!
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    size: number; // Float!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width?: number | null; // Int
  }
  UploadFileEntity: {};
  UploadFileEntityResponse: {};
  UploadFileEntityResponseCollection: {};
  UploadFileRelationResponseCollection: {};
  UsersPermissionsCreateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // root type
    jwt?: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    documentId: string; // ID!
    email?: string | null; // String
    id: string; // ID!
    role?: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // root type
    description?: string | null; // String
    id: string; // ID!
    name: string; // String!
    type?: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // root type
    action: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: {};
  UsersPermissionsPermissionEntityResponse: {};
  UsersPermissionsPermissionEntityResponseCollection: {};
  UsersPermissionsPermissionRelationResponseCollection: {};
  UsersPermissionsRole: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    documentId: string; // ID!
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    type?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsRoleEntity: {};
  UsersPermissionsRoleEntityResponse: {};
  UsersPermissionsRoleEntityResponseCollection: {};
  UsersPermissionsRoleRelationResponseCollection: {};
  UsersPermissionsUpdateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    email: string; // String!
    provider?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: {};
  UsersPermissionsUserEntityResponse: {};
  UsersPermissionsUserEntityResponseCollection: {};
  UsersPermissionsUserRelationResponseCollection: {};
  Video: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    slug: string; // String!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  VideoEntity: {};
  VideoEntityResponse: {};
  VideoEntityResponseCollection: {};
  VideoRelationResponseCollection: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
  ExperienceSectionsDynamicZone: NexusGenRootTypes['ComponentSectionsCta'] | NexusGenRootTypes['ComponentSectionsInfoBlocks'] | NexusGenRootTypes['ComponentSectionsMediaCollection'] | NexusGenRootTypes['ComponentSectionsPromoBanner'] | NexusGenRootTypes['Error'];
  GenericMorph: NexusGenRootTypes['ComponentSectionsCta'] | NexusGenRootTypes['ComponentSectionsInfoBlock'] | NexusGenRootTypes['ComponentSectionsInfoBlocks'] | NexusGenRootTypes['ComponentSectionsMediaCollection'] | NexusGenRootTypes['ComponentSectionsMediaCollectionItem'] | NexusGenRootTypes['ComponentSectionsPromoBanner'] | NexusGenRootTypes['Experience'] | NexusGenRootTypes['I18NLocale'] | NexusGenRootTypes['ReviewWorkflowsWorkflow'] | NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | NexusGenRootTypes['UploadFile'] | NexusGenRootTypes['UsersPermissionsPermission'] | NexusGenRootTypes['UsersPermissionsRole'] | NexusGenRootTypes['UsersPermissionsUser'] | NexusGenRootTypes['Video'];
}

export type NexusGenRootTypes = NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  ComponentSectionsCta: { // field return type
    body: string; // String!
    buttonLabel: string; // String!
    buttonLink: string; // String!
    heading: string; // String!
    id: string; // ID!
  }
  ComponentSectionsInfoBlock: { // field return type
    description: string; // String!
    icon: string; // String!
    id: string; // ID!
    title: string; // String!
  }
  ComponentSectionsInfoBlocks: { // field return type
    blocks: Array<NexusGenRootTypes['ComponentSectionsInfoBlock'] | null> | null; // [ComponentSectionsInfoBlock]
    description: string | null; // String
    heading: string | null; // String
    id: string; // ID!
    intro: string | null; // String
  }
  ComponentSectionsMediaCollection: { // field return type
    categoryLabel: string | null; // String
    ctaLink: string | null; // String
    description: string | null; // String
    id: string; // ID!
    items: Array<NexusGenRootTypes['ComponentSectionsMediaCollectionItem'] | null> | null; // [ComponentSectionsMediaCollectionItem]
    showItemNumbers: boolean | null; // Boolean
    subtitle: string | null; // String
    title: string | null; // String
    variant: NexusGenEnums['ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT']; // ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT!
  }
  ComponentSectionsMediaCollectionItem: { // field return type
    id: string; // ID!
    imageOverride: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    subtitleOverride: string | null; // String
    titleOverride: string | null; // String
    video: NexusGenRootTypes['Video'] | null; // Video
  }
  ComponentSectionsPromoBanner: { // field return type
    ctaLink: string; // String!
    description: string; // String!
    heading: string; // String!
    id: string; // ID!
    intro: string | null; // String
  }
  DeleteMutationResponse: { // field return type
    documentId: string; // ID!
  }
  Error: { // field return type
    code: string; // String!
    message: string | null; // String
  }
  Experience: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    isHomepage: boolean | null; // Boolean
    locale: string | null; // String
    localizations: Array<NexusGenRootTypes['Experience'] | null>; // [Experience]!
    localizations_connection: NexusGenRootTypes['ExperienceRelationResponseCollection'] | null; // ExperienceRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    sections: Array<NexusGenRootTypes['ExperienceSectionsDynamicZone'] | null> | null; // [ExperienceSectionsDynamicZone]
    slug: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ExperienceEntity: { // field return type
    attributes: NexusGenRootTypes['Experience'] | null; // Experience
    id: string | null; // ID
  }
  ExperienceEntityResponse: { // field return type
    data: NexusGenRootTypes['Experience'] | null; // Experience
  }
  ExperienceEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['Experience'][]; // [Experience!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  ExperienceRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['Experience'][]; // [Experience!]!
  }
  I18NLocale: { // field return type
    code: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: { // field return type
    attributes: NexusGenRootTypes['I18NLocale'] | null; // I18NLocale
    id: string | null; // ID
  }
  I18NLocaleEntityResponse: { // field return type
    data: NexusGenRootTypes['I18NLocale'] | null; // I18NLocale
  }
  I18NLocaleEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['I18NLocale'][]; // [I18NLocale!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  I18NLocaleRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['I18NLocale'][]; // [I18NLocale!]!
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    createExperience: NexusGenRootTypes['Experience'] | null; // Experience
    createReviewWorkflowsWorkflow: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
    createReviewWorkflowsWorkflowStage: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
    createUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsCreateRolePayload'] | null; // UsersPermissionsCreateRolePayload
    createUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    createVideo: NexusGenRootTypes['Video'] | null; // Video
    deleteExperience: NexusGenRootTypes['DeleteMutationResponse'] | null; // DeleteMutationResponse
    deleteReviewWorkflowsWorkflow: NexusGenRootTypes['DeleteMutationResponse'] | null; // DeleteMutationResponse
    deleteReviewWorkflowsWorkflowStage: NexusGenRootTypes['DeleteMutationResponse'] | null; // DeleteMutationResponse
    deleteUploadFile: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    deleteUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsDeleteRolePayload'] | null; // UsersPermissionsDeleteRolePayload
    deleteUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    deleteVideo: NexusGenRootTypes['DeleteMutationResponse'] | null; // DeleteMutationResponse
    emailConfirmation: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    forgotPassword: NexusGenRootTypes['UsersPermissionsPasswordPayload'] | null; // UsersPermissionsPasswordPayload
    login: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    register: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    resetPassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    updateExperience: NexusGenRootTypes['Experience'] | null; // Experience
    updateReviewWorkflowsWorkflow: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
    updateReviewWorkflowsWorkflowStage: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
    updateUploadFile: NexusGenRootTypes['UploadFile']; // UploadFile!
    updateUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsUpdateRolePayload'] | null; // UsersPermissionsUpdateRolePayload
    updateUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    updateVideo: NexusGenRootTypes['Video'] | null; // Video
  }
  Pagination: { // field return type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Query: { // field return type
    experience: NexusGenRootTypes['Experience'] | null; // Experience
    experiences: Array<NexusGenRootTypes['Experience'] | null>; // [Experience]!
    experiences_connection: NexusGenRootTypes['ExperienceEntityResponseCollection'] | null; // ExperienceEntityResponseCollection
    i18NLocale: NexusGenRootTypes['I18NLocale'] | null; // I18NLocale
    i18NLocales: Array<NexusGenRootTypes['I18NLocale'] | null>; // [I18NLocale]!
    i18NLocales_connection: NexusGenRootTypes['I18NLocaleEntityResponseCollection'] | null; // I18NLocaleEntityResponseCollection
    me: NexusGenRootTypes['UsersPermissionsMe'] | null; // UsersPermissionsMe
    reviewWorkflowsWorkflow: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
    reviewWorkflowsWorkflowStage: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
    reviewWorkflowsWorkflowStages: Array<NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null>; // [ReviewWorkflowsWorkflowStage]!
    reviewWorkflowsWorkflowStages_connection: NexusGenRootTypes['ReviewWorkflowsWorkflowStageEntityResponseCollection'] | null; // ReviewWorkflowsWorkflowStageEntityResponseCollection
    reviewWorkflowsWorkflows: Array<NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null>; // [ReviewWorkflowsWorkflow]!
    reviewWorkflowsWorkflows_connection: NexusGenRootTypes['ReviewWorkflowsWorkflowEntityResponseCollection'] | null; // ReviewWorkflowsWorkflowEntityResponseCollection
    uploadFile: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    uploadFiles: Array<NexusGenRootTypes['UploadFile'] | null>; // [UploadFile]!
    uploadFiles_connection: NexusGenRootTypes['UploadFileEntityResponseCollection'] | null; // UploadFileEntityResponseCollection
    usersPermissionsRole: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    usersPermissionsRoles: Array<NexusGenRootTypes['UsersPermissionsRole'] | null>; // [UsersPermissionsRole]!
    usersPermissionsRoles_connection: NexusGenRootTypes['UsersPermissionsRoleEntityResponseCollection'] | null; // UsersPermissionsRoleEntityResponseCollection
    usersPermissionsUser: NexusGenRootTypes['UsersPermissionsUser'] | null; // UsersPermissionsUser
    usersPermissionsUsers: Array<NexusGenRootTypes['UsersPermissionsUser'] | null>; // [UsersPermissionsUser]!
    usersPermissionsUsers_connection: NexusGenRootTypes['UsersPermissionsUserEntityResponseCollection'] | null; // UsersPermissionsUserEntityResponseCollection
    video: NexusGenRootTypes['Video'] | null; // Video
    videos: Array<NexusGenRootTypes['Video'] | null>; // [Video]!
    videos_connection: NexusGenRootTypes['VideoEntityResponseCollection'] | null; // VideoEntityResponseCollection
  }
  ResponseCollectionMeta: { // field return type
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  ReviewWorkflowsWorkflow: { // field return type
    contentTypes: NexusGenScalars['JSON']; // JSON!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name: string; // String!
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    stageRequiredToPublish: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
    stages: Array<NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null>; // [ReviewWorkflowsWorkflowStage]!
    stages_connection: NexusGenRootTypes['ReviewWorkflowsWorkflowStageRelationResponseCollection'] | null; // ReviewWorkflowsWorkflowStageRelationResponseCollection
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ReviewWorkflowsWorkflowEntity: { // field return type
    attributes: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
    id: string | null; // ID
  }
  ReviewWorkflowsWorkflowEntityResponse: { // field return type
    data: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
  }
  ReviewWorkflowsWorkflowEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['ReviewWorkflowsWorkflow'][]; // [ReviewWorkflowsWorkflow!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  ReviewWorkflowsWorkflowRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['ReviewWorkflowsWorkflow'][]; // [ReviewWorkflowsWorkflow!]!
  }
  ReviewWorkflowsWorkflowStage: { // field return type
    color: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    name: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    workflow: NexusGenRootTypes['ReviewWorkflowsWorkflow'] | null; // ReviewWorkflowsWorkflow
  }
  ReviewWorkflowsWorkflowStageEntity: { // field return type
    attributes: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
    id: string | null; // ID
  }
  ReviewWorkflowsWorkflowStageEntityResponse: { // field return type
    data: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'] | null; // ReviewWorkflowsWorkflowStage
  }
  ReviewWorkflowsWorkflowStageEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'][]; // [ReviewWorkflowsWorkflowStage!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  ReviewWorkflowsWorkflowStageRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['ReviewWorkflowsWorkflowStage'][]; // [ReviewWorkflowsWorkflowStage!]!
  }
  UploadFile: { // field return type
    alternativeText: string | null; // String
    caption: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    ext: string | null; // String
    focalPoint: NexusGenScalars['JSON'] | null; // JSON
    formats: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl: string | null; // String
    provider: string; // String!
    provider_metadata: NexusGenScalars['JSON'] | null; // JSON
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    related: Array<NexusGenRootTypes['GenericMorph'] | null> | null; // [GenericMorph]
    size: number; // Float!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width: number | null; // Int
  }
  UploadFileEntity: { // field return type
    attributes: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    id: string | null; // ID
  }
  UploadFileEntityResponse: { // field return type
    data: NexusGenRootTypes['UploadFile'] | null; // UploadFile
  }
  UploadFileEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UploadFile'][]; // [UploadFile!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  UploadFileRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UploadFile'][]; // [UploadFile!]!
  }
  UsersPermissionsCreateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // field return type
    jwt: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    documentId: string; // ID!
    email: string | null; // String
    id: string; // ID!
    role: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // field return type
    description: string | null; // String
    id: string; // ID!
    name: string; // String!
    type: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // field return type
    action: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    role: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsPermission'] | null; // UsersPermissionsPermission
    id: string | null; // ID
  }
  UsersPermissionsPermissionEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermission'] | null; // UsersPermissionsPermission
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsPermission'][]; // [UsersPermissionsPermission!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsPermission'][]; // [UsersPermissionsPermission!]!
  }
  UsersPermissionsRole: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    documentId: string; // ID!
    name: string; // String!
    permissions: Array<NexusGenRootTypes['UsersPermissionsPermission'] | null>; // [UsersPermissionsPermission]!
    permissions_connection: NexusGenRootTypes['UsersPermissionsPermissionRelationResponseCollection'] | null; // UsersPermissionsPermissionRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    type: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    users: Array<NexusGenRootTypes['UsersPermissionsUser'] | null>; // [UsersPermissionsUser]!
    users_connection: NexusGenRootTypes['UsersPermissionsUserRelationResponseCollection'] | null; // UsersPermissionsUserRelationResponseCollection
  }
  UsersPermissionsRoleEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    id: string | null; // ID
  }
  UsersPermissionsRoleEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsRole'][]; // [UsersPermissionsRole!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsRole'][]; // [UsersPermissionsRole!]!
  }
  UsersPermissionsUpdateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    email: string; // String!
    provider: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    role: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsUser'] | null; // UsersPermissionsUser
    id: string | null; // ID
  }
  UsersPermissionsUserEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUser'] | null; // UsersPermissionsUser
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsUser'][]; // [UsersPermissionsUser!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['UsersPermissionsUser'][]; // [UsersPermissionsUser!]!
  }
  Video: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    documentId: string; // ID!
    image: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    slug: string; // String!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  VideoEntity: { // field return type
    attributes: NexusGenRootTypes['Video'] | null; // Video
    id: string | null; // ID
  }
  VideoEntityResponse: { // field return type
    data: NexusGenRootTypes['Video'] | null; // Video
  }
  VideoEntityResponseCollection: { // field return type
    nodes: NexusGenRootTypes['Video'][]; // [Video!]!
    pageInfo: NexusGenRootTypes['Pagination']; // Pagination!
  }
  VideoRelationResponseCollection: { // field return type
    nodes: NexusGenRootTypes['Video'][]; // [Video!]!
  }
}

export interface NexusGenFieldTypeNames {
  ComponentSectionsCta: { // field return type name
    body: 'String'
    buttonLabel: 'String'
    buttonLink: 'String'
    heading: 'String'
    id: 'ID'
  }
  ComponentSectionsInfoBlock: { // field return type name
    description: 'String'
    icon: 'String'
    id: 'ID'
    title: 'String'
  }
  ComponentSectionsInfoBlocks: { // field return type name
    blocks: 'ComponentSectionsInfoBlock'
    description: 'String'
    heading: 'String'
    id: 'ID'
    intro: 'String'
  }
  ComponentSectionsMediaCollection: { // field return type name
    categoryLabel: 'String'
    ctaLink: 'String'
    description: 'String'
    id: 'ID'
    items: 'ComponentSectionsMediaCollectionItem'
    showItemNumbers: 'Boolean'
    subtitle: 'String'
    title: 'String'
    variant: 'ENUM_COMPONENTSECTIONSMEDIACOLLECTION_VARIANT'
  }
  ComponentSectionsMediaCollectionItem: { // field return type name
    id: 'ID'
    imageOverride: 'UploadFile'
    subtitleOverride: 'String'
    titleOverride: 'String'
    video: 'Video'
  }
  ComponentSectionsPromoBanner: { // field return type name
    ctaLink: 'String'
    description: 'String'
    heading: 'String'
    id: 'ID'
    intro: 'String'
  }
  DeleteMutationResponse: { // field return type name
    documentId: 'ID'
  }
  Error: { // field return type name
    code: 'String'
    message: 'String'
  }
  Experience: { // field return type name
    createdAt: 'DateTime'
    documentId: 'ID'
    isHomepage: 'Boolean'
    locale: 'String'
    localizations: 'Experience'
    localizations_connection: 'ExperienceRelationResponseCollection'
    publishedAt: 'DateTime'
    sections: 'ExperienceSectionsDynamicZone'
    slug: 'String'
    updatedAt: 'DateTime'
  }
  ExperienceEntity: { // field return type name
    attributes: 'Experience'
    id: 'ID'
  }
  ExperienceEntityResponse: { // field return type name
    data: 'Experience'
  }
  ExperienceEntityResponseCollection: { // field return type name
    nodes: 'Experience'
    pageInfo: 'Pagination'
  }
  ExperienceRelationResponseCollection: { // field return type name
    nodes: 'Experience'
  }
  I18NLocale: { // field return type name
    code: 'String'
    createdAt: 'DateTime'
    documentId: 'ID'
    name: 'String'
    publishedAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  I18NLocaleEntity: { // field return type name
    attributes: 'I18NLocale'
    id: 'ID'
  }
  I18NLocaleEntityResponse: { // field return type name
    data: 'I18NLocale'
  }
  I18NLocaleEntityResponseCollection: { // field return type name
    nodes: 'I18NLocale'
    pageInfo: 'Pagination'
  }
  I18NLocaleRelationResponseCollection: { // field return type name
    nodes: 'I18NLocale'
  }
  Mutation: { // field return type name
    changePassword: 'UsersPermissionsLoginPayload'
    createExperience: 'Experience'
    createReviewWorkflowsWorkflow: 'ReviewWorkflowsWorkflow'
    createReviewWorkflowsWorkflowStage: 'ReviewWorkflowsWorkflowStage'
    createUsersPermissionsRole: 'UsersPermissionsCreateRolePayload'
    createUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    createVideo: 'Video'
    deleteExperience: 'DeleteMutationResponse'
    deleteReviewWorkflowsWorkflow: 'DeleteMutationResponse'
    deleteReviewWorkflowsWorkflowStage: 'DeleteMutationResponse'
    deleteUploadFile: 'UploadFile'
    deleteUsersPermissionsRole: 'UsersPermissionsDeleteRolePayload'
    deleteUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    deleteVideo: 'DeleteMutationResponse'
    emailConfirmation: 'UsersPermissionsLoginPayload'
    forgotPassword: 'UsersPermissionsPasswordPayload'
    login: 'UsersPermissionsLoginPayload'
    register: 'UsersPermissionsLoginPayload'
    resetPassword: 'UsersPermissionsLoginPayload'
    updateExperience: 'Experience'
    updateReviewWorkflowsWorkflow: 'ReviewWorkflowsWorkflow'
    updateReviewWorkflowsWorkflowStage: 'ReviewWorkflowsWorkflowStage'
    updateUploadFile: 'UploadFile'
    updateUsersPermissionsRole: 'UsersPermissionsUpdateRolePayload'
    updateUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    updateVideo: 'Video'
  }
  Pagination: { // field return type name
    page: 'Int'
    pageCount: 'Int'
    pageSize: 'Int'
    total: 'Int'
  }
  Query: { // field return type name
    experience: 'Experience'
    experiences: 'Experience'
    experiences_connection: 'ExperienceEntityResponseCollection'
    i18NLocale: 'I18NLocale'
    i18NLocales: 'I18NLocale'
    i18NLocales_connection: 'I18NLocaleEntityResponseCollection'
    me: 'UsersPermissionsMe'
    reviewWorkflowsWorkflow: 'ReviewWorkflowsWorkflow'
    reviewWorkflowsWorkflowStage: 'ReviewWorkflowsWorkflowStage'
    reviewWorkflowsWorkflowStages: 'ReviewWorkflowsWorkflowStage'
    reviewWorkflowsWorkflowStages_connection: 'ReviewWorkflowsWorkflowStageEntityResponseCollection'
    reviewWorkflowsWorkflows: 'ReviewWorkflowsWorkflow'
    reviewWorkflowsWorkflows_connection: 'ReviewWorkflowsWorkflowEntityResponseCollection'
    uploadFile: 'UploadFile'
    uploadFiles: 'UploadFile'
    uploadFiles_connection: 'UploadFileEntityResponseCollection'
    usersPermissionsRole: 'UsersPermissionsRole'
    usersPermissionsRoles: 'UsersPermissionsRole'
    usersPermissionsRoles_connection: 'UsersPermissionsRoleEntityResponseCollection'
    usersPermissionsUser: 'UsersPermissionsUser'
    usersPermissionsUsers: 'UsersPermissionsUser'
    usersPermissionsUsers_connection: 'UsersPermissionsUserEntityResponseCollection'
    video: 'Video'
    videos: 'Video'
    videos_connection: 'VideoEntityResponseCollection'
  }
  ResponseCollectionMeta: { // field return type name
    pagination: 'Pagination'
  }
  ReviewWorkflowsWorkflow: { // field return type name
    contentTypes: 'JSON'
    createdAt: 'DateTime'
    documentId: 'ID'
    name: 'String'
    publishedAt: 'DateTime'
    stageRequiredToPublish: 'ReviewWorkflowsWorkflowStage'
    stages: 'ReviewWorkflowsWorkflowStage'
    stages_connection: 'ReviewWorkflowsWorkflowStageRelationResponseCollection'
    updatedAt: 'DateTime'
  }
  ReviewWorkflowsWorkflowEntity: { // field return type name
    attributes: 'ReviewWorkflowsWorkflow'
    id: 'ID'
  }
  ReviewWorkflowsWorkflowEntityResponse: { // field return type name
    data: 'ReviewWorkflowsWorkflow'
  }
  ReviewWorkflowsWorkflowEntityResponseCollection: { // field return type name
    nodes: 'ReviewWorkflowsWorkflow'
    pageInfo: 'Pagination'
  }
  ReviewWorkflowsWorkflowRelationResponseCollection: { // field return type name
    nodes: 'ReviewWorkflowsWorkflow'
  }
  ReviewWorkflowsWorkflowStage: { // field return type name
    color: 'String'
    createdAt: 'DateTime'
    documentId: 'ID'
    name: 'String'
    publishedAt: 'DateTime'
    updatedAt: 'DateTime'
    workflow: 'ReviewWorkflowsWorkflow'
  }
  ReviewWorkflowsWorkflowStageEntity: { // field return type name
    attributes: 'ReviewWorkflowsWorkflowStage'
    id: 'ID'
  }
  ReviewWorkflowsWorkflowStageEntityResponse: { // field return type name
    data: 'ReviewWorkflowsWorkflowStage'
  }
  ReviewWorkflowsWorkflowStageEntityResponseCollection: { // field return type name
    nodes: 'ReviewWorkflowsWorkflowStage'
    pageInfo: 'Pagination'
  }
  ReviewWorkflowsWorkflowStageRelationResponseCollection: { // field return type name
    nodes: 'ReviewWorkflowsWorkflowStage'
  }
  UploadFile: { // field return type name
    alternativeText: 'String'
    caption: 'String'
    createdAt: 'DateTime'
    documentId: 'ID'
    ext: 'String'
    focalPoint: 'JSON'
    formats: 'JSON'
    hash: 'String'
    height: 'Int'
    mime: 'String'
    name: 'String'
    previewUrl: 'String'
    provider: 'String'
    provider_metadata: 'JSON'
    publishedAt: 'DateTime'
    related: 'GenericMorph'
    size: 'Float'
    updatedAt: 'DateTime'
    url: 'String'
    width: 'Int'
  }
  UploadFileEntity: { // field return type name
    attributes: 'UploadFile'
    id: 'ID'
  }
  UploadFileEntityResponse: { // field return type name
    data: 'UploadFile'
  }
  UploadFileEntityResponseCollection: { // field return type name
    nodes: 'UploadFile'
    pageInfo: 'Pagination'
  }
  UploadFileRelationResponseCollection: { // field return type name
    nodes: 'UploadFile'
  }
  UsersPermissionsCreateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsDeleteRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsLoginPayload: { // field return type name
    jwt: 'String'
    user: 'UsersPermissionsMe'
  }
  UsersPermissionsMe: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    documentId: 'ID'
    email: 'String'
    id: 'ID'
    role: 'UsersPermissionsMeRole'
    username: 'String'
  }
  UsersPermissionsMeRole: { // field return type name
    description: 'String'
    id: 'ID'
    name: 'String'
    type: 'String'
  }
  UsersPermissionsPasswordPayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsPermission: { // field return type name
    action: 'String'
    createdAt: 'DateTime'
    documentId: 'ID'
    publishedAt: 'DateTime'
    role: 'UsersPermissionsRole'
    updatedAt: 'DateTime'
  }
  UsersPermissionsPermissionEntity: { // field return type name
    attributes: 'UsersPermissionsPermission'
    id: 'ID'
  }
  UsersPermissionsPermissionEntityResponse: { // field return type name
    data: 'UsersPermissionsPermission'
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type name
    nodes: 'UsersPermissionsPermission'
    pageInfo: 'Pagination'
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type name
    nodes: 'UsersPermissionsPermission'
  }
  UsersPermissionsRole: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    documentId: 'ID'
    name: 'String'
    permissions: 'UsersPermissionsPermission'
    permissions_connection: 'UsersPermissionsPermissionRelationResponseCollection'
    publishedAt: 'DateTime'
    type: 'String'
    updatedAt: 'DateTime'
    users: 'UsersPermissionsUser'
    users_connection: 'UsersPermissionsUserRelationResponseCollection'
  }
  UsersPermissionsRoleEntity: { // field return type name
    attributes: 'UsersPermissionsRole'
    id: 'ID'
  }
  UsersPermissionsRoleEntityResponse: { // field return type name
    data: 'UsersPermissionsRole'
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type name
    nodes: 'UsersPermissionsRole'
    pageInfo: 'Pagination'
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type name
    nodes: 'UsersPermissionsRole'
  }
  UsersPermissionsUpdateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsUser: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    createdAt: 'DateTime'
    documentId: 'ID'
    email: 'String'
    provider: 'String'
    publishedAt: 'DateTime'
    role: 'UsersPermissionsRole'
    updatedAt: 'DateTime'
    username: 'String'
  }
  UsersPermissionsUserEntity: { // field return type name
    attributes: 'UsersPermissionsUser'
    id: 'ID'
  }
  UsersPermissionsUserEntityResponse: { // field return type name
    data: 'UsersPermissionsUser'
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type name
    nodes: 'UsersPermissionsUser'
    pageInfo: 'Pagination'
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type name
    nodes: 'UsersPermissionsUser'
  }
  Video: { // field return type name
    createdAt: 'DateTime'
    documentId: 'ID'
    image: 'UploadFile'
    publishedAt: 'DateTime'
    slug: 'String'
    title: 'String'
    updatedAt: 'DateTime'
  }
  VideoEntity: { // field return type name
    attributes: 'Video'
    id: 'ID'
  }
  VideoEntityResponse: { // field return type name
    data: 'Video'
  }
  VideoEntityResponseCollection: { // field return type name
    nodes: 'Video'
    pageInfo: 'Pagination'
  }
  VideoRelationResponseCollection: { // field return type name
    nodes: 'Video'
  }
}

export interface NexusGenArgTypes {
  ComponentSectionsInfoBlocks: {
    blocks: { // args
      filters?: NexusGenInputs['ComponentSectionsInfoBlockFiltersInput'] | null; // ComponentSectionsInfoBlockFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  ComponentSectionsMediaCollection: {
    items: { // args
      filters?: NexusGenInputs['ComponentSectionsMediaCollectionItemFiltersInput'] | null; // ComponentSectionsMediaCollectionItemFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  Experience: {
    localizations: { // args
      filters?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    localizations_connection: { // args
      filters?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  Mutation: {
    changePassword: { // args
      currentPassword: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    createExperience: { // args
      data: NexusGenInputs['ExperienceInput']; // ExperienceInput!
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    createReviewWorkflowsWorkflow: { // args
      data: NexusGenInputs['ReviewWorkflowsWorkflowInput']; // ReviewWorkflowsWorkflowInput!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    createReviewWorkflowsWorkflowStage: { // args
      data: NexusGenInputs['ReviewWorkflowsWorkflowStageInput']; // ReviewWorkflowsWorkflowStageInput!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    createUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
    }
    createUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
    }
    createVideo: { // args
      data: NexusGenInputs['VideoInput']; // VideoInput!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    deleteExperience: { // args
      documentId: string; // ID!
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
    }
    deleteReviewWorkflowsWorkflow: { // args
      documentId: string; // ID!
    }
    deleteReviewWorkflowsWorkflowStage: { // args
      documentId: string; // ID!
    }
    deleteUploadFile: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsRole: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsUser: { // args
      id: string; // ID!
    }
    deleteVideo: { // args
      documentId: string; // ID!
    }
    emailConfirmation: { // args
      confirmation: string; // String!
    }
    forgotPassword: { // args
      email: string; // String!
    }
    login: { // args
      input: NexusGenInputs['UsersPermissionsLoginInput']; // UsersPermissionsLoginInput!
    }
    register: { // args
      input: NexusGenInputs['UsersPermissionsRegisterInput']; // UsersPermissionsRegisterInput!
    }
    resetPassword: { // args
      code: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    updateExperience: { // args
      data: NexusGenInputs['ExperienceInput']; // ExperienceInput!
      documentId: string; // ID!
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    updateReviewWorkflowsWorkflow: { // args
      data: NexusGenInputs['ReviewWorkflowsWorkflowInput']; // ReviewWorkflowsWorkflowInput!
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    updateReviewWorkflowsWorkflowStage: { // args
      data: NexusGenInputs['ReviewWorkflowsWorkflowStageInput']; // ReviewWorkflowsWorkflowStageInput!
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    updateUploadFile: { // args
      id: string; // ID!
      info?: NexusGenInputs['FileInfoInput'] | null; // FileInfoInput
    }
    updateUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
      id: string; // ID!
    }
    updateUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
      id: string; // ID!
    }
    updateVideo: { // args
      data: NexusGenInputs['VideoInput']; // VideoInput!
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
  }
  Query: {
    experience: { // args
      documentId: string; // ID!
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    experiences: { // args
      filters?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    experiences_connection: { // args
      filters?: NexusGenInputs['ExperienceFiltersInput'] | null; // ExperienceFiltersInput
      locale?: NexusGenScalars['I18NLocaleCode'] | null; // I18NLocaleCode
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    i18NLocale: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    i18NLocales: { // args
      filters?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    i18NLocales_connection: { // args
      filters?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflow: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflowStage: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflowStages: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflowStages_connection: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflows: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null; // ReviewWorkflowsWorkflowFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    reviewWorkflowsWorkflows_connection: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowFiltersInput'] | null; // ReviewWorkflowsWorkflowFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    uploadFile: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    uploadFiles: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    uploadFiles_connection: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsRole: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsRoles: { // args
      filters?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsRoles_connection: { // args
      filters?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsUser: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsUsers: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    usersPermissionsUsers_connection: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    video: { // args
      documentId: string; // ID!
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    videos: { // args
      filters?: NexusGenInputs['VideoFiltersInput'] | null; // VideoFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
    videos_connection: { // args
      filters?: NexusGenInputs['VideoFiltersInput'] | null; // VideoFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
      status: NexusGenEnums['PublicationStatus'] | null; // PublicationStatus
    }
  }
  ReviewWorkflowsWorkflow: {
    stages: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    stages_connection: { // args
      filters?: NexusGenInputs['ReviewWorkflowsWorkflowStageFiltersInput'] | null; // ReviewWorkflowsWorkflowStageFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  UsersPermissionsRole: {
    permissions: { // args
      filters?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    permissions_connection: { // args
      filters?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    users: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    users_connection: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  ExperienceSectionsDynamicZone: "ComponentSectionsCta" | "ComponentSectionsInfoBlocks" | "ComponentSectionsMediaCollection" | "ComponentSectionsPromoBanner" | "Error"
  GenericMorph: "ComponentSectionsCta" | "ComponentSectionsInfoBlock" | "ComponentSectionsInfoBlocks" | "ComponentSectionsMediaCollection" | "ComponentSectionsMediaCollectionItem" | "ComponentSectionsPromoBanner" | "Experience" | "I18NLocale" | "ReviewWorkflowsWorkflow" | "ReviewWorkflowsWorkflowStage" | "UploadFile" | "UsersPermissionsPermission" | "UsersPermissionsRole" | "UsersPermissionsUser" | "Video"
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "ExperienceSectionsDynamicZone" | "GenericMorph";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}